{{- if .Values.artifactManager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.artifactManager.service.name }}
  namespace: {{ include "srm.namespace" . }}
  labels:
    {{- include "srm.artifactmanager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.artifactManager.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.artifactManager.service.port }}
      targetPort: {{ .Values.artifactManager.service.targetPort }}
      {{- if and (eq .Values.artifactManager.service.type "NodePort") .Values.artifactManager.service.nodePort }}
      nodePort: {{ .Values.artifactManager.service.nodePort }}
      {{- end }}
  selector:
    {{- include "srm.artifactmanager.selectorLabels" . | nindent 4 }}
{{- end }}
