{{- if .Values.srmcontroller.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.srmcontroller.name }}
  namespace: {{ include "srm.namespace" . }}
  labels:
    {{- include "srm.controller.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.srmcontroller.replicaCount }}
  selector:
    matchLabels:
      {{- include "srm.controller.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- include "srm.controller.selectorLabels" . | nindent 8 }}
      {{- with .Values.commonAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Values.srmcontroller.name }}
          image: "{{ .Values.srmcontroller.image.repository }}:{{ .Values.srmcontroller.image.tag }}"
          imagePullPolicy: {{ .Values.srmcontroller.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.srmcontroller.service.targetPort }}
              protocol: TCP
          env:
            - name: KUBERNETES_MASTER_IP
              value: {{ .Values.srmcontroller.env.kubernetesMasterIp | quote }}
            - name: KUBERNETES_MASTER_PORT
              value: {{ .Values.srmcontroller.env.kubernetesMasterPort | quote }}
            - name: KUBERNETES_USERNAME
              value: {{ .Values.srmcontroller.env.kubernetesUsername | quote }}
            - name: K8S_NAMESPACE
              value: {{ .Values.srmcontroller.env.k8sNamespace | quote }}
            - name: EMP_STORAGE_URI
              value: {{ .Values.srmcontroller.env.empStorageUri | quote }}
            - name: KUBERNETES_MASTER_TOKEN
              value: {{ .Values.srmcontroller.env.kubernetesMasterToken | quote }}
            - name: ARTIFACT_MANAGER_ADDRESS
              value: {{ .Values.srmcontroller.env.artifactManagerAddress | quote }}
            - name: EDGE_CLOUD_ADAPTER_NAME
              value: {{ .Values.srmcontroller.env.edgeCloudAdapterName | quote }}
            - name: ADAPTER_BASE_URL
              value: {{ .Values.srmcontroller.env.adapterBaseUrl | quote }}
            - name: PLATFORM_PROVIDER
              value: {{ .Values.srmcontroller.env.platformProvider | quote }}
            - name: NETWORK_ADAPTER_NAME
              value: {{ .Values.srmcontroller.env.networkAdapterName | quote }}
            - name: NETWORK_ADAPTER_BASE_URL
              value: {{ .Values.srmcontroller.env.networkAdapterBaseUrl | quote }}
            - name: SCS_AS_ID
              value: {{ .Values.srmcontroller.env.scsAsId | quote }}
          {{- with .Values.srmcontroller.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        #  livenessProbe:
        #    httpGet:
        #      path: /
        #      port: http
        #    initialDelaySeconds: 60
        #    periodSeconds: 10
        #    timeoutSeconds: 5
        #    failureThreshold: 3
        #  readinessProbe:
        #    httpGet:
        #      path: /
        #      port: http
        #    initialDelaySeconds: 30
        #    periodSeconds: 5
        #    timeoutSeconds: 3
        #    failureThreshold: 3
      restartPolicy: Always
{{- end }}
