{{- if and .Values.mongodb.enabled .Values.mongodb.persistence.enabled .Values.mongodb.persistence.createPV }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.mongodb.name }}-pv-volume
  namespace: {{ include "oeg.namespace" . }}
  labels:
    type: local
    app: {{ .Values.mongodb.name }}
    {{- include "oeg.mongodb.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.mongodb.persistence.storageClass }}
  capacity:
    storage: {{ .Values.mongodb.persistence.size }}
  accessModes:
    - {{ .Values.mongodb.persistence.accessMode }}
  {{- if .Values.mongodb.persistence.hostPath.enabled }}
  hostPath:
    path: {{ .Values.mongodb.persistence.hostPath.path | quote }}
  {{- end }}
{{- end }}
