{{- if .Values.mongodb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongodb.name }}
  namespace: {{ include "oeg.namespace" . }}
  labels:
    {{- include "oeg.mongodb.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "oeg.mongodb.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "oeg.mongodb.selectorLabels" . | nindent 8 }}
      {{- with .Values.commonAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Values.mongodb.name }}
          image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
          imagePullPolicy: {{ .Values.mongodb.image.pullPolicy }}
          ports:
            - name: mongodb
              containerPort: {{ .Values.mongodb.service.port }}
              protocol: TCP
          {{- with .Values.mongodb.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.mongodb.persistence.enabled }}
          volumeMounts:
            - name: mongo-db
              mountPath: /data/db
          {{- end }}
      restartPolicy: Always
      {{- if .Values.mongodb.persistence.enabled }}
      volumes:
        - name: mongo-db
          persistentVolumeClaim:
            claimName: {{ .Values.mongodb.name }}
      {{- end }}
{{- end }}
