{{- if .Values.oegcontroller.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.oegcontroller.name }}
  namespace: {{ include "oeg.namespace" . }}
  labels:
    {{- include "oeg.controller.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.oegcontroller.replicaCount }}
  selector:
    matchLabels:
      {{- include "oeg.controller.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- include "oeg.controller.selectorLabels" . | nindent 8 }}
      {{- with .Values.commonAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Values.oegcontroller.name }}
          image: "{{ .Values.oegcontroller.image.repository }}:{{ .Values.oegcontroller.image.tag }}"
          imagePullPolicy: {{ .Values.oegcontroller.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.oegcontroller.service.targetPort }}
              protocol: TCP
          env:
            - name: MONGO_URI
              value: {{ .Values.oegcontroller.env.mongoUri | quote }}
            - name: SRM_HOST
              value: {{ .Values.oegcontroller.env.srmHost | quote }}
            - name: FEDERATION_MANAGER_HOST
              value: {{ .Values.oegcontroller.env.federationManagerHost | quote }}
            - name: PARTNER_API_ROOT
              value: {{ .Values.oegcontroller.env.partnerApiRoot | quote }}
            - name: TOKEN_ENDPOINT
              value: {{ .Values.oegcontroller.env.tokenEndpoint | quote }}
          {{- with .Values.oegcontroller.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        #  livenessProbe:
         #   httpGet:
          #    path: /
          #    port: http
          #  initialDelaySeconds: 30
          #  periodSeconds: 10
          #  timeoutSeconds: 5
          #  failureThreshold: 3
         # readinessProbe:
         #   httpGet:
         #     path: /
         #     port: http
         #   initialDelaySeconds: 10
         #   periodSeconds: 5
         #   timeoutSeconds: 3
         #   failureThreshold: 3
      restartPolicy: Always
{{- end }}
