{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.keycloak.service.name }}
  namespace: {{ include "federation-manager.namespace" . }}
  labels:
    {{- include "federation-manager.keycloak.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.keycloak.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.keycloak.service.port }}
      targetPort: {{ .Values.keycloak.service.targetPort }}
      {{- if and (eq .Values.keycloak.service.type "NodePort") .Values.keycloak.service.nodePort }}
      nodePort: {{ .Values.keycloak.service.nodePort }}
      {{- end }}
  selector:
    {{- include "federation-manager.keycloak.selectorLabels" . | nindent 4 }}
{{- end }}
