{{- if and .Values.keycloak.enabled .Values.keycloak.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-ingress
  namespace: {{ include "federation-manager.namespace" . }}
  labels:
    {{- include "federation-manager.keycloak.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.keycloak.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.keycloak.ingress.className }}
  rules:
    - host: {{ .Values.keycloak.ingress.host }}
      http:
        paths:
          - path: {{ .Values.keycloak.ingress.path }}
            pathType: {{ .Values.keycloak.ingress.pathType }}
            backend:
              service:
                name: {{ .Values.keycloak.service.name }}
                port:
                  number: {{ .Values.keycloak.service.port }}
{{- end }}
