{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.name }}
  namespace: {{ include "federation-manager.namespace" . }}
  labels:
    app: {{ .Values.mongodb.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: {{ .Values.mongodb.service.port }}
  selector:
    app: {{ .Values.mongodb.name }}
{{- end }}

