{{- if and .Values.mongodb.enabled .Values.mongodb.persistence.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.mongodb.name }}-pv
  labels:
    app: {{ .Values.mongodb.name }}
spec:
  capacity:
    storage: {{ .Values.mongodb.persistence.size | quote }}
  accessModes:
    - {{ .Values.mongodb.persistence.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.mongodb.persistence.storageClass | default "mongodb-fm-storage" }}
  hostPath:
    path: {{ .Values.mongodb.persistence.hostPath | default "/mnt/data/mongodb_fm" }}
    type: DirectoryOrCreate
{{- end }}
